jest.mock('../../dist/shared/config/redis',()=>({isRedisAvailable:jest.fn(()=>true),redisClient:{set:jest.fn(async()=> 'OK')}}));
const redis=require('../../dist/shared/config/redis'),crypto=require('../../dist/shared/security/third-party-crypto'),{IntegrationService}=require('../../dist/nest/overview/integration.service');
describe('native third-party signature protocol',()=>{
 let credential,db,service,request,headers,prior;const secret='test-only-secret';
 beforeAll(()=>{prior=process.env.THIRD_PARTY_SECRET_ENCRYPTION_KEY;process.env.THIRD_PARTY_SECRET_ENCRYPTION_KEY='32'.repeat(32);});
 afterAll(()=>{if(prior===undefined)delete process.env.THIRD_PARTY_SECRET_ENCRYPTION_KEY;else process.env.THIRD_PARTY_SECRET_ENCRYPTION_KEY=prior;});
 beforeEach(()=>{
  jest.clearAllMocks();redis.isRedisAvailable.mockReturnValue(true);redis.redisClient.set.mockResolvedValue('OK');
  credential={id:'key',client_name:'test',api_key:'public-key',status:'active',scopes:['integration:ping'],...crypto.encryptSecret(secret)};
  db={owl_third_party_api_keys:{findFirst:jest.fn(async()=>credential),update:jest.fn(async()=>({}))},owl_third_party_api_call_logs:{create:jest.fn(async()=>({}))}};service=new IntegrationService(db);
  request={method:'GET',originalUrl:'/api/public/integration/ping?b=2&a=1',query:{b:'2',a:'1'},rawBody:Buffer.from(''),clientIp:'127.0.0.1',get:name=>headers[name]};const timestamp=String(Date.now()),nonce='nonce';headers={'X-API-Key':'public-key','X-Timestamp':timestamp,'X-Nonce':nonce,'X-Signature':crypto.createSignature(crypto.buildCanonicalRequest({...request,path:'/api/public/integration/ping',timestamp,nonce}),secret)};
 });
 const expectAudit=status=>expect(db.owl_third_party_api_call_logs.create).toHaveBeenLastCalledWith({data:expect.objectContaining({response_code:status})});
 it('validates canonical query, updates use time and saves a completed audit',async()=>{expect((await service.ping(request)).client).toBe('test');expect(redis.redisClient.set).toHaveBeenCalledWith('third-party:nonce:key:nonce','1',{NX:true,EX:600});expectAudit(200);expect(db.owl_third_party_api_keys.findFirst).toHaveBeenCalledWith({where:{api_key:'public-key',deletedAt:null}});});
 it('rejects missing headers, old timestamps and tampered query before consuming nonce',async()=>{delete headers['X-Nonce'];await expect(service.ping(request)).rejects.toMatchObject({statusCode:400});headers['X-Nonce']='nonce';headers['X-Timestamp']='1';await expect(service.ping(request)).rejects.toMatchObject({statusCode:400});headers['X-Timestamp']=String(Date.now());request.query.b='tampered';await expect(service.ping(request)).rejects.toMatchObject({statusCode:401});expect(redis.redisClient.set).not.toHaveBeenCalled();expectAudit(401);});
 it('fails closed when Redis is unavailable, nonce repeated or scope absent',async()=>{redis.isRedisAvailable.mockReturnValue(false);await expect(service.ping(request)).rejects.toMatchObject({statusCode:503});redis.isRedisAvailable.mockReturnValue(true);redis.redisClient.set.mockResolvedValue(null);await expect(service.ping(request)).rejects.toMatchObject({statusCode:409});redis.redisClient.set.mockResolvedValue('OK');credential.scopes=[];await expect(service.ping(request)).rejects.toMatchObject({statusCode:403});expectAudit(403);});
 it('rejects disabled, expired and deleted credentials',async()=>{credential.status='disabled';await expect(service.ping(request)).rejects.toMatchObject({statusCode:403});credential.status='active';credential.expires_at=new Date(0);await expect(service.ping(request)).rejects.toMatchObject({statusCode:403});db.owl_third_party_api_keys.findFirst.mockResolvedValue(null);await expect(service.ping(request)).rejects.toMatchObject({statusCode:401});expect(redis.redisClient.set).not.toHaveBeenCalled();});
});
