import { ApiController } from './api.controller';
import { MaskingService } from './data-security/masking.service';
import {WatermarkController} from './overview/watermark.controller';
import {WatermarkService} from './overview/watermark.service';
import {DictionaryController} from './overview/dictionary.controller';
import {DictionaryService} from './overview/dictionary.service';
import {DashboardController} from './overview/dashboard.controller';
import {DashboardService} from './overview/dashboard.service';
import {DashboardWidgetController} from './overview/dashboard-widget.controller';
import {DashboardWidgetService} from './overview/dashboard-widget.service';
import {IntegrationController} from './overview/integration.controller';
import {IntegrationService} from './overview/integration.service';
import {ApiBuilderService} from './dynamic/api-builder.service';
import {SqlApiKeysService} from './dynamic/api-key.service';
import {ApiExecutorService} from './dynamic/api-executor.service';
import {SqlService} from './dynamic/sql.service';
import {GenericService} from './dynamic/generic.service';
import {DbReaderService} from './dynamic/db-reader.service';
import {ModuleConfigService} from './dynamic/module-config.service';
import {GenerationHistoryService} from './dynamic/generation-history.service';
import {CodeGeneratorService} from './dynamic/code-generator.service';
import {BusinessTableService} from './dynamic/business-table.service';
import {SqlParserService} from './dynamic/sql-parser.service';
import {ApiBuilderKeysController} from './dynamic/api-builder-keys.controller';
import {ApiExecutorController} from './dynamic/api-executor.controller';
import {CustomApiController} from './dynamic/api-executor.controller';
import {ApiBuilderController} from './dynamic/api-builder.controller';
import {GeneratorController} from './dynamic/generator.controller';
import {GenericController} from './dynamic/generic.controller';
import {DynamicGuard} from './dynamic/dynamic.guard';
import {LogService} from './log/log.service';
import {MetricsService} from './monitor/metrics.service';
import {AlertService} from './monitor/alert.service';
import {ServerMonitorService} from './monitor/server-monitor.service';
import {ApiMonitorService} from './monitor/api-monitor.service';
import {NotificationSocket} from './notification/socket.service';
import {EmailTasksService} from './notification/email-tasks.service';
import {EmailTemplatesService} from './notification/templates.service';
import {MailTransport} from './notification/email.service';
import {EmailService} from './notification/email.service';
import {NotificationSettingsService} from './notification/settings.service';
import {NotificationsService} from './notification/notifications.service';
import {LogController} from './log/log.controller';
import {MonitorController} from './monitor/monitor.controller';
import {AlertController} from './monitor/alert.controller';
import {ServerMonitorController} from './monitor/server-monitor.controller';
import {ApiMonitorController} from './monitor/api-monitor.controller';
import {EmailTaskController} from './notification/email-task.controller';
import {EmailTemplateController} from './notification/email-template.controller';
import {EmailController} from './notification/email.controller';
import {SettingsController} from './notification/settings.controller';
import {NotificationController} from './notification/notification.controller';
import { ThirdPartyKeysController } from './data-security/third-party-keys.controller';
import { DataSecurityController } from './data-security/data-security.controller';
import { UploadStreamController } from './storage/upload-stream.controller';
import { UploadController } from './storage/upload.controller';
import { FilePermissionController } from './storage/file-permission.controller';
import { FileShareController } from './storage/file-share.controller';
import { FolderController } from './storage/folder.controller';
import { FileController } from './storage/file.controller';
import { ThirdPartyKeysService } from './data-security/third-party-keys.service';
import { SecurityEffects } from './data-security/security.effects';
import { DataSecurityService } from './data-security/data-security.service';
import { UploadsService } from './storage/uploads.service';
import { StorageObjects } from './storage/storage-objects.service';
import { SharesService } from './storage/shares.service';
import { FilePermissionsService } from './storage/file-permissions.service';
import { FoldersService } from './storage/folders.service';
import { FilesService } from './storage/files.service';
import { CaptchaController } from './identity/captcha.controller';
import { DepartmentController } from './identity/department.controller';
import { MenuController } from './identity/menu.controller';
import { PermissionController } from './identity/permission.controller';
import { RoleController } from './identity/role.controller';
import { UserController } from './identity/user.controller';
import { SMSController } from './identity/sms.controller';
import { AuthController } from './identity/auth.controller';
import { IdentityGuard } from './identity/identity.guard';
import { IdentityEffects } from './identity/identity.effects';
import { DepartmentsService } from './identity/departments.service';
import { MenusService } from './identity/menus.service';
import { PermissionsService } from './identity/permissions.service';
import { RolesService } from './identity/roles.service';
import { UsersService } from './identity/users.service';
import { AuthService } from './identity/auth.service';
import { Module } from '@nestjs/common';
import { PrismaService } from './database/prisma.service';
import { SystemConfigService } from './system-config/system-config.service';
import { SystemConfigController } from './system-config/system-config.controller';
import { HealthController } from './health.controller';
import { AdminGuard } from './compatibility/admin.guard';
import { LegacyLifecycle } from './compatibility/lifecycle.service';

@Module({ controllers: [ApiController, WatermarkController, DictionaryController, DashboardController, DashboardWidgetController, IntegrationController, ApiBuilderKeysController, ApiExecutorController, CustomApiController, ApiBuilderController, GeneratorController, GenericController, SettingsController, NotificationController, EmailController, EmailTemplateController, EmailTaskController, ApiMonitorController, ServerMonitorController, AlertController, MonitorController, LogController, FileController, FolderController, FileShareController, FilePermissionController, UploadController, UploadStreamController, DataSecurityController, ThirdPartyKeysController, AuthController, SMSController, UserController, RoleController, PermissionController, MenuController, DepartmentController, CaptchaController, HealthController, SystemConfigController], providers: [MaskingService, WatermarkService, DictionaryService, DashboardService, DashboardWidgetService, IntegrationService, DynamicGuard, ApiBuilderService, SqlApiKeysService, ApiExecutorService, SqlService, GenericService, DbReaderService, ModuleConfigService, GenerationHistoryService, CodeGeneratorService, BusinessTableService, SqlParserService, NotificationsService, NotificationSettingsService, EmailService, MailTransport, EmailTemplatesService, EmailTasksService, NotificationSocket, ApiMonitorService, ServerMonitorService, AlertService, MetricsService, LogService, FilesService, FoldersService, FilePermissionsService, SharesService, StorageObjects, UploadsService, DataSecurityService, SecurityEffects, ThirdPartyKeysService, AuthService, UsersService, RolesService, PermissionsService, MenusService, DepartmentsService, IdentityEffects, IdentityGuard, PrismaService, SystemConfigService, AdminGuard, LegacyLifecycle] })
export class AppModule {}
