-- 删除旧的 ENUM 类型（如果存在），确保幂等性
DROP TYPE IF EXISTS enum_owl_api_interfaces_method CASCADE;
DROP TYPE IF EXISTS enum_owl_api_interfaces_status CASCADE;
DROP TYPE IF EXISTS enum_owl_api_keys_status CASCADE;
DROP TYPE IF EXISTS enum_owl_dashboard_widgets_chart_type CASCADE;
DROP TYPE IF EXISTS enum_owl_dashboard_widgets_widget_type CASCADE;
DROP TYPE IF EXISTS enum_owl_departments_status CASCADE;
DROP TYPE IF EXISTS enum_owl_email_logs_status CASCADE;
DROP TYPE IF EXISTS enum_owl_menus_menu_type CASCADE;
DROP TYPE IF EXISTS enum_owl_menus_status CASCADE;
DROP TYPE IF EXISTS enum_owl_menus_type CASCADE;
DROP TYPE IF EXISTS enum_owl_notifications_type CASCADE;
DROP TYPE IF EXISTS enum_owl_roles_status CASCADE;
DROP TYPE IF EXISTS enum_owl_sensitive_fields_mask_type CASCADE;
DROP TYPE IF EXISTS enum_owl_system_configs_login_layout CASCADE;
DROP TYPE IF EXISTS enum_owl_system_configs_login_method CASCADE;
DROP TYPE IF EXISTS enum_owl_system_configs_registration_method CASCADE;
DROP TYPE IF EXISTS enum_owl_system_configs_theme_mode CASCADE;
DROP TYPE IF EXISTS enum_owl_third_party_api_keys_status CASCADE;
DROP TYPE IF EXISTS enum_owl_user_sessions_status CASCADE;
DROP TYPE IF EXISTS enum_owl_users_status CASCADE;

-- 创建所有 ENUM 类型
CREATE TYPE enum_owl_api_interfaces_method AS ENUM ('GET', 'POST', 'PUT', 'DELETE');
CREATE TYPE enum_owl_api_interfaces_status AS ENUM ('active', 'inactive');
CREATE TYPE enum_owl_api_keys_status AS ENUM ('active', 'inactive');
CREATE TYPE enum_owl_dashboard_widgets_chart_type AS ENUM ('line', 'bar', 'area', 'pie');
CREATE TYPE enum_owl_dashboard_widgets_widget_type AS ENUM ('metric', 'chart');
CREATE TYPE enum_owl_departments_status AS ENUM ('active', 'inactive');
CREATE TYPE enum_owl_email_logs_status AS ENUM ('pending', 'sent', 'failed');
CREATE TYPE enum_owl_menus_menu_type AS ENUM ('business', 'system');
CREATE TYPE enum_owl_menus_status AS ENUM ('active', 'inactive');
CREATE TYPE enum_owl_menus_type AS ENUM ('menu', 'button', 'link');
CREATE TYPE enum_owl_notifications_type AS ENUM ('info', 'system', 'warning', 'error', 'success');
CREATE TYPE enum_owl_roles_status AS ENUM ('active', 'inactive');
CREATE TYPE enum_owl_sensitive_fields_mask_type AS ENUM ('phone', 'email', 'id_card', 'bank_card', 'name', 'address', 'custom');
CREATE TYPE enum_owl_system_configs_login_layout AS ENUM ('center', 'left-image', 'right-image');
CREATE TYPE enum_owl_system_configs_login_method AS ENUM ('password', 'sms', 'both');
CREATE TYPE enum_owl_system_configs_registration_method AS ENUM ('password', 'sms', 'both');
CREATE TYPE enum_owl_system_configs_theme_mode AS ENUM ('light', 'dark', 'auto');
CREATE TYPE enum_owl_third_party_api_keys_status AS ENUM ('active', 'inactive', 'expired');
CREATE TYPE enum_owl_user_sessions_status AS ENUM ('active', 'kicked', 'expired');
CREATE TYPE enum_owl_users_status AS ENUM ('active', 'inactive', 'banned');
